// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: proto/employee.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EmployeeService_GetEmployee_FullMethodName               = "/employee.EmployeeService/GetEmployee"
	EmployeeService_GetEmployees_FullMethodName              = "/employee.EmployeeService/GetEmployees"
	EmployeeService_AddEmployees_FullMethodName              = "/employee.EmployeeService/AddEmployees"
	EmployeeService_BidirectionalGetEmployees_FullMethodName = "/employee.EmployeeService/BidirectionalGetEmployees"
)

// EmployeeServiceClient is the client API for EmployeeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmployeeServiceClient interface {
	GetEmployee(ctx context.Context, in *EmployeeRequest, opts ...grpc.CallOption) (*EmployeeResponse, error)
	GetEmployees(ctx context.Context, in *EmployeeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EmployeeResponse], error)
	AddEmployees(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Employee, EmployeeCount], error)
	BidirectionalGetEmployees(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EmployeeRequest, EmployeeResponse], error)
}

type employeeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEmployeeServiceClient(cc grpc.ClientConnInterface) EmployeeServiceClient {
	return &employeeServiceClient{cc}
}

func (c *employeeServiceClient) GetEmployee(ctx context.Context, in *EmployeeRequest, opts ...grpc.CallOption) (*EmployeeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmployeeResponse)
	err := c.cc.Invoke(ctx, EmployeeService_GetEmployee_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeServiceClient) GetEmployees(ctx context.Context, in *EmployeeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EmployeeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EmployeeService_ServiceDesc.Streams[0], EmployeeService_GetEmployees_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EmployeeRequest, EmployeeResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EmployeeService_GetEmployeesClient = grpc.ServerStreamingClient[EmployeeResponse]

func (c *employeeServiceClient) AddEmployees(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Employee, EmployeeCount], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EmployeeService_ServiceDesc.Streams[1], EmployeeService_AddEmployees_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Employee, EmployeeCount]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EmployeeService_AddEmployeesClient = grpc.ClientStreamingClient[Employee, EmployeeCount]

func (c *employeeServiceClient) BidirectionalGetEmployees(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EmployeeRequest, EmployeeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EmployeeService_ServiceDesc.Streams[2], EmployeeService_BidirectionalGetEmployees_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EmployeeRequest, EmployeeResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EmployeeService_BidirectionalGetEmployeesClient = grpc.BidiStreamingClient[EmployeeRequest, EmployeeResponse]

// EmployeeServiceServer is the server API for EmployeeService service.
// All implementations must embed UnimplementedEmployeeServiceServer
// for forward compatibility.
type EmployeeServiceServer interface {
	GetEmployee(context.Context, *EmployeeRequest) (*EmployeeResponse, error)
	GetEmployees(*EmployeeRequest, grpc.ServerStreamingServer[EmployeeResponse]) error
	AddEmployees(grpc.ClientStreamingServer[Employee, EmployeeCount]) error
	BidirectionalGetEmployees(grpc.BidiStreamingServer[EmployeeRequest, EmployeeResponse]) error
	mustEmbedUnimplementedEmployeeServiceServer()
}

// UnimplementedEmployeeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEmployeeServiceServer struct{}

func (UnimplementedEmployeeServiceServer) GetEmployee(context.Context, *EmployeeRequest) (*EmployeeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEmployee not implemented")
}
func (UnimplementedEmployeeServiceServer) GetEmployees(*EmployeeRequest, grpc.ServerStreamingServer[EmployeeResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetEmployees not implemented")
}
func (UnimplementedEmployeeServiceServer) AddEmployees(grpc.ClientStreamingServer[Employee, EmployeeCount]) error {
	return status.Errorf(codes.Unimplemented, "method AddEmployees not implemented")
}
func (UnimplementedEmployeeServiceServer) BidirectionalGetEmployees(grpc.BidiStreamingServer[EmployeeRequest, EmployeeResponse]) error {
	return status.Errorf(codes.Unimplemented, "method BidirectionalGetEmployees not implemented")
}
func (UnimplementedEmployeeServiceServer) mustEmbedUnimplementedEmployeeServiceServer() {}
func (UnimplementedEmployeeServiceServer) testEmbeddedByValue()                         {}

// UnsafeEmployeeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmployeeServiceServer will
// result in compilation errors.
type UnsafeEmployeeServiceServer interface {
	mustEmbedUnimplementedEmployeeServiceServer()
}

func RegisterEmployeeServiceServer(s grpc.ServiceRegistrar, srv EmployeeServiceServer) {
	// If the following call pancis, it indicates UnimplementedEmployeeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EmployeeService_ServiceDesc, srv)
}

func _EmployeeService_GetEmployee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmployeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServiceServer).GetEmployee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmployeeService_GetEmployee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServiceServer).GetEmployee(ctx, req.(*EmployeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmployeeService_GetEmployees_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EmployeeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EmployeeServiceServer).GetEmployees(m, &grpc.GenericServerStream[EmployeeRequest, EmployeeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EmployeeService_GetEmployeesServer = grpc.ServerStreamingServer[EmployeeResponse]

func _EmployeeService_AddEmployees_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EmployeeServiceServer).AddEmployees(&grpc.GenericServerStream[Employee, EmployeeCount]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EmployeeService_AddEmployeesServer = grpc.ClientStreamingServer[Employee, EmployeeCount]

func _EmployeeService_BidirectionalGetEmployees_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EmployeeServiceServer).BidirectionalGetEmployees(&grpc.GenericServerStream[EmployeeRequest, EmployeeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EmployeeService_BidirectionalGetEmployeesServer = grpc.BidiStreamingServer[EmployeeRequest, EmployeeResponse]

// EmployeeService_ServiceDesc is the grpc.ServiceDesc for EmployeeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmployeeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "employee.EmployeeService",
	HandlerType: (*EmployeeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEmployee",
			Handler:    _EmployeeService_GetEmployee_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetEmployees",
			Handler:       _EmployeeService_GetEmployees_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "AddEmployees",
			Handler:       _EmployeeService_AddEmployees_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "BidirectionalGetEmployees",
			Handler:       _EmployeeService_BidirectionalGetEmployees_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/employee.proto",
}
